pos-django-main/pos/urls.py
from django.urls import path
from pos import views

app_name = 'pos'

urlpatterns = [
    path('home', views.home, name='home'),
    path('new-order/', views.buat_order, name='buat-order'),
    path('daftar-menu/<int:order_id>/', views.daftar_menu, name='daftar-menu'),
    path('tambah-item/<int:order_id>/<int:menu_id>/', views.tambah_item, name='tambah-item'),
    path('kurangi-qty/<int:order_id>/<int:menu_id>/', views.kurangi_qty, name='kurangi-qty'),
    path('tambah-qty/<int:order_id>/<int:menu_id>/', views.tambah_qty, name='tambah-qty'),
    path('order-aktif/', views.order_aktif, name='order-aktif'),
    path('print-order/<int:id>/', views.print_order, name='print-order'),
    path('batal-order/<int:id>/', views.batal_order, name='batal-order'),
    path('bayar-order/<int:id>/', views.bayar_order, name='bayar-order'),
    path('laporan-penjualan/', views.laporan_penjualan, name='laporan-penjualan'),

    # URL untuk fungsi cetak_struk
    path('cetak-struk/<int:id>/', views.cetak_struk, name='cetak-struk'),  
    # URL untuk menambah menu
    path('menu/tambah/', views.tambah_menu, name='tambah-menu'),
    # URL untuk menghapus menu
    path('menu/hapus/<int:menu_id>/', views.hapus_menu, name='hapus-menu'),
    # URL untuk edit menu
    path('menu/edit/<int:menu_id>/', views.edit_menu, name='edit-menu'),
    # Master Menu
    path('master-menu/', views.master_menu, name='master-menu'),
    # Kontrol Fitur
    path('fitur/', views.fitur_list, name='fitur_list'),  # Daftar fitur
    path('fitur/toggle/<int:fitur_id>/', views.fitur_toggle, name='fitur_toggle'),  # Toggle fitur aktif/non-aktif

]

pos-django-main/pos_caffe_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pos/', include('pos.urls', namespace='pos')),
    path('', include('users.urls')),
]

pos-django-main/pos/models.py
from django.db import models

"""
Migrations for 'pos':
  pos/migrations/0001_initial.py
    - Create model Menu
    - Create model Order
    - Create model Item
"""


class Menu(models.Model):
    nama = models.CharField(max_length=100)
    price = models.PositiveIntegerField(default=10000)
    image = models.URLField()
    
    def __str__(self):
        return self.nama
    

class Order(models.Model):
    tanggal = models.DateField(auto_now=True)
    meja = models.CharField(max_length=100)
    pelanggan = models.CharField(max_length=100)
    total = models.PositiveIntegerField(default=0)
    dibayar = models.PositiveIntegerField(default=0)
    kembali = models.PositiveIntegerField(default=0)
    selesai = models.BooleanField(default=False)

    def __str__(self):
        return self.meja

    
class Item(models.Model):
    order = models.ForeignKey(Order,
                              related_name='order_item', 
                              on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, 
                             related_name='menu_item', 
                             on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    harga = models.PositiveIntegerField(default=0)
    subtotal = models.PositiveIntegerField(default=0)
    catatan = models.CharField(max_length=200, blank=True, null=True)
    dikirim = models.BooleanField(default=False)
    
    def __str__(self):
        return self.menu.nama


class Fitur(models.Model):
    nama = models.CharField(max_length=100)
    aktif = models.BooleanField(default=True)

    def __str__(self):
        return self.nama
    

    
    

pos-django-main/pos/forms.py
from django import forms

from pos.models import Order, Menu

# New Order 
class BuatOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'meja',
            'pelanggan',
        ]

# Bayar
class BayarOrderForm(forms.Form):
    dibayar = forms.IntegerField()

# Menu
class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['nama', 'price', 'image']
        widgets = {
            'image': forms.URLInput(attrs={'placeholder': 'Masukkan URL gambar'})
        }

# Edit Menu
class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['nama','price', 'image']  # Tentukan field apa saja yang bisa di-edit

pos-django-main/pos/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ValidationError
from pos.forms import BuatOrderForm, BayarOrderForm, MenuForm
from pos.models import Menu, Order, Item, Menu, Fitur
from django.contrib import messages
import datetime
from django.contrib.auth.decorators import login_required, user_passes_test
from users.views import  bukan_level_kasir

@login_required
def home(request):
    return render(request, 'pos/home.html')

@login_required
def daftar_menu(request, order_id):
    menu_list = Menu.objects.all()
    order = get_object_or_404(Order, pk=order_id)

    page = request.GET.get('page', 1)
    
    paginator = Paginator(menu_list, 10)
    
    try:
        menus = paginator.page(page)
    except PageNotAnInteger:
        menus = paginator.page(1)
    except EmptyPage:
        menus = paginator.page(paginator.num_pages)
    
    return render(request, 
                  'pos/daftar_menu.html', 
                  {'menus': menus,
                   'order': order})

@login_required
def buat_order(request):
    if request.method == 'POST':
        form = BuatOrderForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.total = 0
            obj.dibayar = 0
            obj.kembali = 0
            obj.save()
            return redirect('pos:daftar-menu', order_id=obj.pk)

    else:
        form = BuatOrderForm()
    return render(request, 'pos/buat_order.html', {'form': form})

@login_required
def order_aktif(request):
    order_list = Order.objects.filter(selesai=False)
    page = request.GET.get('page', 1)
    paginator = Paginator(order_list, 10)

    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)

    return render(request,
                  'pos/order_aktif.html',
                  {'orders': orders})

@login_required
def tambah_item(request, order_id, menu_id):
    order = get_object_or_404(Order, id=order_id)
    menu = get_object_or_404(Menu, id=menu_id)
    item, created = Item.objects.get_or_create(
        menu=menu,
        order=order
    )

    item.qty = item.qty + 0
    item.harga = menu.price
    item.subtotal = item.harga * item.qty
    item.save()

    items = Item.objects.filter(order=order).aggregate(total=Sum('subtotal'))
    order.total = items['total']
    order.save()

    return redirect('pos:daftar-menu', order_id=order.id)

@login_required
def tambah_qty(request, order_id, menu_id):
    order = get_object_or_404(Order, id=order_id)
    menu = get_object_or_404(Menu, id=menu_id)
    
    # Cek apakah item sudah ada dalam pesanan
    item = Item.objects.filter(menu=menu, order=order).first()
    
    if not item:
        # Menampilkan pesan error jika item belum ada
        messages.error(request, 'Item belum dipilih. Silakan pesan menu terlebih dahulu.')
        return redirect('pos:daftar-menu', order_id=order.id)
    
    # Jika item sudah ada, lakukan penambahan jumlah
    item.qty += 1
    item.harga = menu.price
    item.subtotal = item.harga * item.qty
    item.save()

    # Update total pada order
    items = Item.objects.filter(order=order).aggregate(total=Sum('subtotal'))
    order.total = items['total']
    order.save()

    return redirect('pos:daftar-menu', order_id=order.id)

@login_required
def kurangi_qty(request, order_id, menu_id):
    order = get_object_or_404(Order, id=order_id)
    menu = get_object_or_404(Menu, id=menu_id)
    
    # Cek apakah item sudah ada dalam pesanan
    item = Item.objects.filter(menu=menu, order=order).first()
    
    if not item:
        # Menampilkan pesan error jika item belum ada
        messages.error(request, 'Item belum dipilih. Silakan pesan menu terlebih dahulu.')
        return redirect('pos:daftar-menu', order_id=order.id)

    if item.qty <= 1:
        # Menampilkan pesan error jika kuantitas item tidak bisa dikurangi lebih lanjut
        messages.error(request, 'Tidak bisa mengurangi jumlah item lebih dari ini.')
        item.delete()  # Jika kuantitas 1, item dihapus
        return redirect('pos:daftar-menu', order_id=order.id)

    # Jika item sudah ada dan qty lebih dari 1, lakukan pengurangan
    item.qty -= 1
    item.harga = menu.price
    item.subtotal = item.harga * item.qty
    item.save()

    # Update total pada order
    items = Item.objects.filter(order=order).aggregate(total=Sum('subtotal'))
    order.total = items['total']
    order.save()

    return redirect('pos:daftar-menu', order_id=order.id)

@login_required
def batal_order(request, id):
    order = get_object_or_404(Order, id=id)
    order.delete()
    return redirect('pos:order-aktif')

@login_required
def bayar_order(request, id):
    order = get_object_or_404(Order, id=id, selesai=False)

    if request.method == 'POST':
        form = BayarOrderForm(data=request.POST)

        if form.is_valid():
            dibayar = form.cleaned_data['dibayar']

            if dibayar < order.total:
                raise ValidationError('Uang Anda kurang!')

            order.kembali = dibayar - order.total
            order.dibayar = dibayar
            order.selesai = True
            order.save()

            return render(
                request,
                'pos/print_order.html',
                {'order': order}
            )

    else:
        form = BayarOrderForm()

    return render(request,
                  'pos/bayar_order.html',
                  {'order': order, 'form': form})

@login_required
def print_order(request, id):
    order = get_object_or_404(Order, id=id)
    return render(request, 'pos/print_order.html', {'order': order})

@login_required
def cetak_struk(request, id):
    # Ambil data pesanan berdasarkan ID
    order = get_object_or_404(Order, id=id)
    
    # Ambil semua item yang ada di pesanan
    items = Item.objects.filter(order=order)
    
    # Jika pesanan tidak memiliki item, tampilkan pesan error
    if not items:
        messages.error(request, "Order ini tidak memiliki item!")
        return redirect('pos:laporan-penjualan')
    
    # Render template cetak_struk.html untuk menampilkan struk
    return render(
        request,
        'pos/cetak_struk.html',  # Template yang akan menampilkan struk
        {'order': order, 'items': items}  # Data yang dikirim ke template
    )

@login_required
# Laporan Penjualan  
def laporan_penjualan(request):
    """
    # Cek apakah fitur 'laporan_penjualan' aktif
    fitur_laporan_penjualan = Fitur.objects.filter(nama="laporan_penjualan", aktif=True).exists()

    if not fitur_laporan_penjualan:
        # Jika fitur tidak aktif, tampilkan pesan atau redirect ke halaman lain
        messages.error(request, "Anda tidak memiliki akses ke Laporan Penjualan!!!")
        return redirect('pos:home')  # Contoh redireksi ke halaman home
    """
    # Cek apakah pengguna adalah bagian dari grup 'Level_Kasir'
    if request.user.groups.filter(name='Level_Kasir').exists():
        # Jika pengguna dalam grup 'Level_Kasir', hanya tampilkan laporan hari ini
        order = Order.objects.filter(tanggal=datetime.date.today())
        jumlah = sum(order.total for order in order)
        context = {'order': order, 'jumlah': jumlah}
        return render(request, 'pos/laporan_penjualan.html', context)

    # Pastikan form POST mengandung tanggal awal dan akhir
    if request.method == "POST":
        awal_tgl = request.POST.get('awal_tgl')
        akhir_tgl = request.POST.get('akhir_tgl')

        # Cek apakah tanggal awal dan akhir ada di inputan
        if not awal_tgl or not akhir_tgl:
            # Jika tanggal tidak diisi, tampilkan pesan error
            messages.error(request, 'Harap pilih tanggal mulai dan tanggal akhir terlebih dahulu.')
            return render(request, 'pos/laporan_penjualan.html')

        # Jika tanggal ada, lanjutkan dengan pemrosesan laporan
        order = Order.objects.filter(tanggal__range=[awal_tgl, akhir_tgl])
        jumlah = sum(order.total for order in order)
        context = {'order': order, 'jumlah': jumlah}
        return render(request, 'pos/laporan_penjualan.html', context)
    
    else:
        # Jika request tidak POST (misalnya GET), tampilkan laporan untuk hari ini
        order = Order.objects.filter(tanggal=datetime.date.today())
        jumlah = sum(order.total for order in order)
        context = {'order': order, 'jumlah': jumlah}
        return render(request, 'pos/laporan_penjualan.html', context)



### Kelola Menu : ###
# 1. Tambah Menu
@login_required
def tambah_menu(request):
    if request.method == 'POST':
        form = MenuForm(request.POST)
        if form.is_valid():
            # Menyimpan data menu baru ke dalam database
            form.save()
            messages.success(request, 'Menu berhasil ditambahkan!')
            return redirect('pos:master-menu')  # Arahkan ke halaman daftar menu setelah menambah menu
    else:
        form = MenuForm()

    return render(request, 'pos/tambah_menu.html', {'form': form})

# 2. Hapus Menu
@login_required
def hapus_menu(request, menu_id):
    menu = get_object_or_404(Menu, id=menu_id)  # Mencari menu berdasarkan ID
    menu.delete()  # Menghapus menu dari database
    messages.success(request, 'Menu berhasil dihapus!')
    return redirect('pos:master-menu')  # Arahkan ke halaman daftar menu setelah menu dihapus

# 3. Edit Menu
@login_required
def edit_menu(request, menu_id):
    menu = get_object_or_404(Menu, id=menu_id)

    if request.method == 'POST':
        form = MenuForm(request.POST, instance=menu)  # Mengisi form dengan data menu yang ada
        if form.is_valid():
            form.save()  # Simpan perubahan
            return redirect('pos:master-menu')  # Arahkan kembali ke daftar menu
    else:

pos-django-main/templates/pos/bayar_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Bayar Order{% endblock %}


{% block content %}
  <div class="row mt-5 d-flex justify-content-center">
    <div class="col-lg-5 ">

      <div class="card bg-dark shadow">
        <div class="card-body">
          <h2 class="card-title">IDR {{ order.total }}</h2>
          <p>Pembayaran oleh {{ order.pelanggan }}</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form | crispy }}
            <button type="submit"
                    class="btn btn-success btn-lg btn-block"
            >
              Bayar
            </button>
          </form>
        </div>
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/buat_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}New Order{% endblock %}


{% block content %}
  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="display-3 text-shadow d-flex justify-content-center">
        New Order
      </h1>
      <h5 class="mt-4 d-flex justify-content-center">
        Masukan nomor meja dan nama pelanggan
      </h4>
    </div>
  </div>
  <div class="row mt-3 d-flex justify-content-center">
    <div class="col-lg-5 ">

      <div class="card bg-dark">
        <div class="card-body">
          <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"
                    class="btn btn-success btn-lg btn-block"
            >
              Simpan
            </button>
          </form>
        </div>
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/daftar_menu.html
{% extends "base.html" %}

{% block title %}Daftar Menu{% endblock %}

{% block content %}

{% if messages %}
  <div class="alert alert-danger" id="message-alert">
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  </div>

  <script type="text/javascript">
    // Tunggu beberapa detik sebelum menghilangkan pesan
    setTimeout(function() {
      var alert = document.getElementById("message-alert");
      if (alert) {
        alert.style.display = "none";
      }
    }, 5000);  // Pesan akan hilang setelah 5 detik (5000 ms)
  </script>
{% endif %}

<div class="row mt-5">
  <div class="col-md-12">
    <h1 class="display-2 text-shadow d-flex justify-content-center">
      Daftar Menu
    </h1>
    <h4 class="mt-4 d-flex justify-content-center">
      Pilih menu sesuai selera Anda
    </h4>
  </div>
</div>

<div class="row mt-3">
  <div class="col-lg-12">
    {% include "pos/components/order_info.html" with order=order %}
  </div>
</div>

<div class="row mt-3">
  <div class="col-lg-12">
    <!-- Gantilah card-columns dengan grid -->
    <div class="row">
      {% for menu in menus %}
        <div class="col-lg-2 col-md-4 col-sm-6 mb-4">  <!-- 5 items per row -->
          <div class="card bg-warning text-center text-dark border-dark shadow">
            <img src="{{ menu.image }}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ menu.nama }}</h5>
              <h6 class="card-text">IDR {{ menu.price }}</h6> 
              <a href="{% url 'pos:tambah-item' order_id=order.id menu_id=menu.id %}" class="btn btn-dark btn-block btn-sm">pesan</a>
              <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'pos:tambah-qty' order_id=order.id menu_id=menu.id %}" class="btn btn-success btn-sm">(+)</a>
                <a href="{% url 'pos:kurangi-qty' order_id=order.id menu_id=menu.id %}" class="btn btn-danger btn-sm">(-)</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

pos-django-main/templates/pos/daftar_menu_V1.html
{% extends "base.html" %}

{% block title %}Daftar Menu{% endblock %}


{% block content %}

  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="display-2 text-shadow d-flex justify-content-center">
        Daftar Menu
      </h1>
      <h4 class="mt-4 d-flex justify-content-center">
        Pilih menu sesuai selera Anda
      </h4>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-lg-12">
      {% include "pos/components/order_info.html" with order=order %}
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-12">

      <div class="card-columns">
        {% for menu in menus %}
        <div class="card bg-warning text-center text-dark border-dark shadow">
          <img src="{{ menu.image }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h1 class="card-title">{{ menu.nama }}</h1>
            <h3 class="card-text">IDR {{ menu.price }}</h3>
            <a href="{% url 'pos:tambah-item' order_id=order.id menu_id=menu.id %}" class="btn btn-dark btn-block btn-lg">pesan</a>
            <a href="{% url 'pos:tambah-qty' order_id=order.id menu_id=menu.id %}" class="btn btn-dark btn-block btn-lg">(+)</a>
            <a href="{% url 'pos:kurangi-qty' order_id=order.id menu_id=menu.id %}" class="btn btn-dark btn-block btn-lg">(-)</a>

          </div>
        </div>
        {% endfor %}
      </div>

    </div>

  </div>
{% endblock %}

pos-django-main/templates/pos/edit_menu.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Menu{% endblock %}


{% block content %}
<div class="row mt-5">
    <div class="col-md-12">
        <h1 class="display-2 text-shadow d-flex justify-content-center">
            Edit Menu
        </h1>
    </div>
</div>

<div class="row mt-3 d-flex justify-content-center">
    <div class="col-lg-5 ">
        <div class="card bg-dark">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success btn-lg btn-block">
                        Simpan Perubahan
                    </button>
                </form>
                <a href="{% url 'pos:master-menu' %}">Kembali ke Daftar Menu</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pos-django-main/templates/pos/fitur_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Fitur</title>
</head>
<body>
    <h1>Daftar Fitur</h1>
    
    <table border="1">
        <thead>
            <tr>
                <th>Nama Fitur</th>
                <th>Status</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            {% for fitur in fitur %}
            <tr>
                <td>{{ fitur.nama }}</td>
                <td>
                    {% if fitur.aktif %}
                    Aktif
                    {% else %}
                    Non-Aktif
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'pos:fitur_toggle' fitur.id %}">
                        {% if fitur.aktif %}
                        Non-Aktifkan
                        {% else %}
                        Aktifkan
                        {% endif %}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
</body>
</html>

pos-django-main/templates/pos/home.html
{% extends "base.html" %}

{% block title %}I-POS{% endblock %}

{% block content %}

{% if messages %}
  <div class="alert alert-danger" id="message-alert">
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  </div>

  <script type="text/javascript">
    // Tunggu beberapa detik sebelum menghilangkan pesan
    setTimeout(function() {
      var alert = document.getElementById("message-alert");
      if (alert) {
        alert.style.display = "none";  // Menyembunyikan pesan setelah 5 detik
      }
    }, 5000);  // Pesan akan hilang setelah 5000 milidetik (5 detik)
  </script>
{% endif %}

<div class="row mt-5">
  <div class="col-md-12">
    <h1 class=" display-2 d-flex justify-content-center">
      I-POS
    </h1>
    <hr>
  </div>
</div>

<div class="row mt-3 d-flex justify-content-center text-light">

  <div class="col-xl-12 mb-4">
    <a href="{% url 'pos:buat-order' %}" class="text-decoration-none">
      <div class="card bg-success text-dark">
        <div class="card-body shadow d-flex justify-content-center">
          <h4 class="display-3 text-pink card-title text-center">
            New Order
          </h4>
        </div>
      </div>
    </a>
  </div>
  <div class="col-xl-12 mb-4">
    <a href="{% url 'pos:order-aktif' %}" class="text-decoration-none">
      <div class="card bg-warning text-dark">
        <div class="card-body shadow d-flex justify-content-center">
          <h4 class="display-3 card-title text-center">
            Active Order
          </h4>
        </div>
      </div>
    </a>
  </div>
</div>
{% endblock %}

pos-django-main/templates/pos/master_menu.html
{% extends 'base.html' %}

{% block title %}Master Menu{% endblock %}

{% block content %}
{% load humanize %}

<style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      padding: 8px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }

    tr:hover {background-color: green;}
</style>

{% if messages %}
  <div class="alert alert-success" id="message-alert">
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
  </div>

  <script type="text/javascript">
    // Tunggu beberapa detik sebelum menghilangkan pesan
    setTimeout(function() {
      var alert = document.getElementById("message-alert");
      if (alert) {
        alert.style.display = "none";  // Menyembunyikan pesan setelah 5 detik
      }
    }, 5000);  // Pesan akan hilang setelah 5000 milidetik (5 detik)
  </script>
{% endif %}

<h1 class="display-3 text-shadow d-flex justify-content-center">Daftar Menu</h1>
<a href="{% url 'pos:tambah-menu' %}" class="btn btn-success btn-sm">Tambah Menu Baru</a>

<hr>

<table style="width:100%" id="reportTable">
    <thead>
        <tr>
            <th>Nama Menu</th>
            <th>Harga(Rp)</th>
            <th>Gambar</th>
            <th>Aksi</th>
        </tr>
    </thead>
    <tbody>
        {% for menu in menus %}
            <tr>
                <td>{{ menu.nama }}</td>
                <td>{{ menu.price|intcomma }}</td>
                <td><img src="{{ menu.image }}" alt="{{ menu.nama }}" style="width: 100px; height: 100px;"></td>
                <td>
                    <!-- Tautan untuk mengedit menu -->
                    <a href="{% url 'pos:edit-menu' menu.id %}" class="btn btn-warning btn-sm">Edit</a> |
                    <!-- Tautan untuk menghapus menu -->
                    <a href="{% url 'pos:hapus-menu' menu.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin ingin menghapus menu ini?')">Hapus</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if menus.has_previous %}
            <a href="?page=1">&laquo; pertama</a>
            <a href="?page={{ menus.previous_page_number }}">sebelumnya</a>
        {% endif %}

        <span class="current">
            Halaman {{ menus.number }} dari {{ menus.paginator.num_pages }}.
        </span>

        {% if menus.has_next %}
            <a href="?page={{ menus.next_page_number }}">selanjutnya</a>
            <a href="?page={{ menus.paginator.num_pages }}">terakhir &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

pos-django-main/templates/pos/order_aktif.html
{% extends "base.html" %}

{% block title %}Daftar Menu{% endblock %}


{% block content %}
  <div class="row mt-5">
    <div class="col-md-12">
      <h1 class="display-3 text-shadow d-flex justify-content-center">
        Order Aktif
      </h1>
      <h5 class="mt-4 text-center">
        Daftar order yang aktif
      </h5>
    </div>
  </div>
<div class="row mt-3">
  <div class="col-lg-12">

    <div class="card-columns">
      {% for order in orders %}
      <div class="card bg-warning text-dark border-dark shadow-lg">
        <div class="card-body">
          <h1 class="card-title">{{ order.meja }}</h1>
          <h3>IDR {{ order.total }}, A/N {{ order.pelanggan }}</h3>
        </div>
        <ul class="list-group list-group-flush bg-warning">
          {% for item in order.order_item.all %}
            <li class="list-group-item text-dark bg-warning">
              {{ item.menu.nama }} <br>
              IDR {{ item.harga }} x {{ item.qty }} = IDR {{ item.subtotal }}
            </li>
          {% empty %}
            <li class="list-group-item text-dark bg-warning">
              Item belum ada!
            </li>
          {% endfor %}
        </ul>
        <div class="card-footer">
          <div class="btn-group d-flex justify-content-end" role="group">
            <a href="{% url 'pos:daftar-menu' order_id=order.id %}"
               class="btn btn-dark btn-lg"
            >
              Tambah Item
            </a>
            <a href="{% url 'pos:bayar-order' id=order.id %}"
               class="btn btn-success btn-lg"
            >
              Bayar
            </a>
            <a href="{% url 'pos:batal-order' id=order.id %}"
               class="btn btn-danger btn-lg"
            >
              Batal
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>

</div>
{% endblock %}